version: '3'
services:
  php:
    build: ./php
    ports:
      - 8080:80
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db